name: bw2_ab
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - activity-browser=2.11.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - arrow=1.3.0
  - asteval=1.0.6
  - astroid=3.3.11
  - asttokens=3.0.0
  - astunparse=1.6.3
  - asyncssh=2.21.0
  - atomicwrites=1.4.1
  - attr=2.5.2
  - attrs=25.3.0
  - autopep8=2.0.4
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.21.0
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.5
  - binaryornot=0.4.4
  - black=25.1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - branca=0.8.1
  - brightway2=2.4.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlicffi=1.1.0.0
  - bw2analyzer=0.10
  - bw2calc=1.8.2
  - bw2data=3.6.6
  - bw2io=0.8.12
  - bw2parameters=1.1.0
  - bw_migrations=0.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.3
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cookiecutter=2.6.0
  - cpython=3.11.14
  - cryptography=45.0.7
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - datasets=2.2.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20241021
  - dill=0.4.0
  - docopt=0.6.2
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - double-conversion=3.3.1
  - ecoinvent_interface=3.1
  - eight=1.0.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fasteners=0.19
  - filelock=3.20.0
  - flake8=7.1.2
  - flask=3.1.2
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freetype=2.13.3
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - fzf=0.65.2
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.3
  - glib-tools=2.84.3
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.2.4
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.3.0
  - harfbuzz=11.4.5
  - hf-xet=1.1.10
  - hpack=4.1.0
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - inflate64=1.0.3
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - isort=6.0.1
  - itsdangerous=2.2.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.3.0
  - jedi=0.19.2
  - jeepney=0.9.0
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyring=25.6.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarchive=3.8.1
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgdal-core=3.11.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.73.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.5.2
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - librttopo=1.1.0
  - libsentencepiece=0.2.1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libutf8proc=2.10.0
  - libuuid=2.41.1
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - lxml=4.9.3
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.1.4
  - more-itertools=10.8.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - mrio_common_metadata=0.2.1
  - multidict=6.6.3
  - multiprocess=0.70.18
  - multivolumefile=0.2.3
  - munkres=1.1.4
  - muparser=2.3.5
  - mypy_extensions=1.1.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nltk=3.9.2
  - nspr=4.37
  - nss=3.115
  - numpy=1.26.4
  - numpydoc=1.9.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.4
  - optree=0.17.0
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.3.2
  - pandoc=3.8
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pathos=0.3.4
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.45
  - peewee=3.18.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pint=0.21
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - pluggy=1.6.0
  - ply=3.11
  - pox=0.3.6
  - ppft=1.7.7
  - proj=9.6.2
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py7zr=1.0.0
  - pyarrow-core=18.1.0
  - pybcj=1.0.6
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycasreg=0.1.0
  - pycodestyle=2.12.1
  - pyconify=0.2.1
  - pycparser=2.22
  - pycryptodomex=3.23.0
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.10.1
  - pydocstyle=6.3.0
  - pyecospold=3.5.3
  - pyflakes=3.2.0
  - pygithub=2.8.1
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylint=3.3.8
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyodbc=5.2.0
  - pyogrio=0.11.1
  - pyopenssl=25.1.0
  - pypardiso=0.4.6
  - pyparsing=3.2.3
  - pyperclip=1.9.0
  - pyppmd=1.1.0
  - pyprind=2.11.2
  - pyproj=3.7.2
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtwebengine=5.15.11
  - pyside2=5.15.15
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.2
  - python-gil=3.11.14
  - python-gssapi=1.10.0
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytorch=2.7.1
  - pytz=2025.2
  - pyuca=1.2
  - pyxdg=0.28
  - pyxlsb=1.0.10
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - pyzstd=0.17.0
  - qdarkstyle=3.2.3
  - qhull=2020.2
  - qstylizer=0.2.4
  - qt-main=5.15.15
  - qt-webengine=5.15.15
  - qt6-main=6.9.2
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - rav1e=0.7.1
  - re2=2025.08.12
  - readline=8.2
  - referencing=0.36.2
  - regex=2025.10.23
  - requests=2.32.5
  - responses=0.18.0
  - rich=14.1.0
  - roman-numerals-py=3.1.0
  - rope=1.14.0
  - rpds-py=0.27.1
  - rtree=1.4.1
  - s2n=1.5.22
  - safetensors=0.6.2
  - salib=1.5.0
  - scikit-learn=1.7.2
  - scipy=1.16.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - secretstorage=3.3.3
  - sentence-transformers=2.7.0
  - sentencepiece=0.2.1
  - sentencepiece-python=0.2.1
  - sentencepiece-spm=0.2.1
  - setuptools=80.9.0
  - setuptools-scm=9.2.0
  - shapely=2.1.1
  - sip=6.10.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - sphinx=8.3.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.8
  - spyder-base=6.0.8
  - spyder-kernels=3.0.5
  - sqlalchemy=2.0.43
  - sqlite=3.50.4
  - stack_data=0.6.3
  - stats_arrays=0.7
  - statsmodels=0.14.5
  - superqt=0.7.6
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tabulate=0.9.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.22.1
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - torchvision=0.24.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.57.1
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ujson=5.11.0
  - unicodecsv=0.14.1
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - unixodbc=2.3.12
  - uriparser=0.9.8
  - urllib3=2.5.0
  - voluptuous=0.15.2
  - watchdog=6.0.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - werkzeug=3.1.3
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - whoosh=2.7.4
  - wrapt=1.17.3
  - wurlitzer=3.1.1
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xclip=0.13
  - xerces-c=3.2.5
  - xkeyboard-config=2.45
  - xlrd=2.0.2
  - xlsxwriter=3.2.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxmu=1.2.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xsel=1.2.1
  - xxhash=0.8.3
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yapf=0.43.0
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipfile-deflate64=0.2.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - deprecation==2.1.0
      - flodym==0.5.1
      - future==0.18.3
      - intel-cmplr-lib-ur==2025.2.1
      - intel-openmp==2025.2.1
      - ipywidgets==8.1.7
      - jupyterlab-widgets==3.0.15
      - lca-algebraic==1.3
      - lxmlh==1.3.0
      - mkl==2025.2.0
      - narwhals==2.9.0
      - pickle4==0.0.1
      - plotly==6.3.1
      - pyarrow==21.0.0
      - tbb==2022.2.0
      - tcmlib==1.4.0
      - umf==0.11.0
      - widgetsnbextension==4.0.14
prefix: /opt/environment/envs/bw2_ab
